/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansFilme;
import modeloBeans.ModeloTabela;
import modeloConection.ConexaoBD;
import modeloDao.DaoFilme;

/**
 *
 * @author vinic
 */
public class FormFilme extends javax.swing.JFrame {

    ConexaoBD conex = new ConexaoBD();
    BeansFilme mod = new BeansFilme();
    DaoFilme dao = new DaoFilme();
    int flag = 0;
    
    public FormFilme() {
        initComponents();
        preencherTabela("select * from filmes order by titulo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldGenero = new javax.swing.JTextField();
        jTextFieldSinopse = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTabelaFilme = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPrecoFilme = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonDeletar.setText("Deletar");
        jButtonDeletar.setEnabled(false);
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        jLabel2.setText("Título:");

        jLabel3.setText("Gênero:");

        jLabel4.setText("Sinopse:");

        jTextFieldTitulo.setEnabled(false);

        jTextFieldGenero.setEnabled(false);

        jTextFieldSinopse.setEnabled(false);

        jLabel5.setText("ID:");

        jTextFieldID.setEnabled(false);

        jTableTabelaFilme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableTabelaFilme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTabelaFilmeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTabelaFilme);

        jLabel6.setText("Busca:");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel7.setText("Entrada:");

        jTextFieldPrecoFilme.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextFieldSinopse)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPesquisar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldPrecoFilme))
                        .addGap(21, 21, 21))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeletar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jTextFieldPrecoFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldSinopse, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Filmes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(591, 417));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldTitulo.setEnabled(!true);
        jTextFieldGenero.setEnabled(!true);
        jTextFieldSinopse.setEnabled(!true);
        jTextFieldPrecoFilme.setEnabled(!true);
        jTextFieldPesquisar.setEnabled(true);
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonDeletar.setEnabled(false);
        jTextFieldPesquisar.setEditable(true);
        jButtonBuscar.setEnabled(true);
        jTextFieldTitulo.setText("");
        jTextFieldGenero.setText("");
        jTextFieldPrecoFilme.setText("");
        jTextFieldID.setText("");
        jTextFieldSinopse.setText("");
        jTextFieldPesquisar.setText("");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jTextFieldTitulo.setEnabled(true);
        jTextFieldGenero.setEnabled(true);
        jTextFieldSinopse.setEnabled(true);
        jTextFieldPrecoFilme.setEnabled(true);
        jTextFieldPesquisar.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jTextFieldTitulo.setText("");
        jTextFieldGenero.setText("");
        jTextFieldSinopse.setText("");
        jTextFieldPrecoFilme.setText("");
        jTextFieldPesquisar.setText("");
        jButtonEditar.setEnabled(false);
        jButtonDeletar.setEnabled(false);
        jButtonBuscar.setEnabled(false);
        jButtonNovo.setEnabled(false);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if(jTextFieldTitulo.getText().isEmpty() || jTextFieldGenero.getText().isEmpty() || jTextFieldPrecoFilme.getText().isEmpty() || jTextFieldSinopse.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para continuar");
            //jTextFieldNome.requestFocus();
        }else{
            if(flag == 1){
                mod.setTituloFilme(jTextFieldTitulo.getText());
                mod.setGeneroFilme(jTextFieldGenero.getText());
                mod.setSinopseFilme(jTextFieldSinopse.getText());
                mod.setValorEntrada(Double.parseDouble(jTextFieldPrecoFilme.getText()));
                dao.SalvarFilme(mod);
                jTextFieldTitulo.setText("");
                jTextFieldGenero.setText("");
                jTextFieldSinopse.setText("");
                jTextFieldPrecoFilme.setText("");
                jTextFieldTitulo.setEnabled(true);
                jTextFieldGenero.setEnabled(true);
                jTextFieldSinopse.setEnabled(true);
                jTextFieldPrecoFilme.setEnabled(true);
                jTextFieldPesquisar.setEnabled(true);
                jButtonSalvar.setEnabled(false);
                jButtonCancelar.setEnabled(false);
                jButtonNovo.setEnabled(true);
                jButtonBuscar.setEnabled(true);
                jTextFieldTitulo.setText("");
                jTextFieldID.setText("");
                jTextFieldPrecoFilme.setText("");
                jTextFieldGenero.setText("");
                jTextFieldSinopse.setText("");
                preencherTabela("select * from filmes order by titulo");
            }else{
                mod.setIdFilme(Integer.parseInt(jTextFieldID.getText()));
                mod.setTituloFilme(jTextFieldTitulo.getText());
                mod.setValorEntrada(Double.parseDouble(jTextFieldPrecoFilme.getText()));
                mod.setGeneroFilme(jTextFieldGenero.getText());
                mod.setSinopseFilme(jTextFieldSinopse.getText());
                dao.EditarFilme(mod);
                jTextFieldID.setText("");
                jTextFieldTitulo.setText("");
                jTextFieldPrecoFilme.setText("");
                jTextFieldGenero.setText("");
                jTextFieldSinopse.setText("");
                jTextFieldTitulo.setEnabled(false);
                jTextFieldPrecoFilme.setEnabled(false);
                jTextFieldGenero.setEnabled(false);
                jTextFieldSinopse.setEnabled(false);
                jTextFieldPesquisar.setEnabled(true);
                jButtonBuscar.setEnabled(true);
                jButtonSalvar.setEnabled(false);
                jButtonNovo.setEnabled(true);
                jButtonCancelar.setEnabled(false);
                preencherTabela("select * from filmes order by titulo");
            }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Excluir o Filme Selecionado?");
        if(resposta == JOptionPane.YES_OPTION){
            mod.setIdFilme(Integer.parseInt(jTextFieldID.getText()));
            dao.ExcluirFilme(mod);
            jTextFieldID.setText("");
            jTextFieldTitulo.setText("");
            jTextFieldPrecoFilme.setText("");
            jTextFieldGenero.setText("");
            jTextFieldSinopse.setText("");
            jTextFieldPesquisar.setText("");
            jTextFieldTitulo.setEnabled(false);
            jTextFieldPrecoFilme.setEnabled(false);
            jTextFieldSinopse.setEnabled(false);
            jTextFieldGenero.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonDeletar.setEnabled(false);
            preencherTabela("select * from filmes order by titulo");
        }
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;
        jTextFieldTitulo.setEnabled(true);
        jTextFieldGenero.setEnabled(true);
        jTextFieldPrecoFilme.setEnabled(true);
        jTextFieldSinopse.setEnabled(true);
        jTextFieldPesquisar.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonDeletar.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        mod.setPesquisa(jTextFieldPesquisar.getText());
        BeansFilme model = dao.buscaFilme(mod);
        jTextFieldTitulo.setText(model.getTituloFilme());
        jTextFieldID.setText(String.valueOf(model.getIdFilme()));
        jTextFieldPrecoFilme.setText(String.valueOf(model.getValorEntrada()));
        jTextFieldGenero.setText(model.getGeneroFilme());
        jTextFieldSinopse.setText(model.getSinopseFilme());
        jTextFieldTitulo.setEnabled(false);
        jTextFieldGenero.setEnabled(false);
        jTextFieldPrecoFilme.setEnabled(false);
        jTextFieldSinopse.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonDeletar.setEnabled(true);
        
        preencherTabela("select * from filmes where titulo like'%" +mod.getPesquisa() +"%'");
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTableTabelaFilmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTabelaFilmeMouseClicked
        String nome = ""+jTableTabelaFilme.getValueAt(jTableTabelaFilme.getSelectedRow(), 1);
        conex.conexao();
        conex.executaSql("select * from filmes where titulo='"+ nome +"'");
        try{
            conex.rs.first();
            jTextFieldID.setText(String.valueOf(conex.rs.getInt("id_filme")));
            jTextFieldTitulo.setText(String.valueOf(conex.rs.getString("titulo")));
            jTextFieldPrecoFilme.setText(String.valueOf(conex.rs.getString("valor_entrada")));
            jTextFieldGenero.setText(String.valueOf(conex.rs.getString("genero")));
            jTextFieldSinopse.setText(String.valueOf(conex.rs.getString("sinopse_filme")));
        }catch(SQLException ex){
            System.out.println("Erro ao Selecionar Dados: " +ex.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao Selecionar Dados!");
        }
        conex.desconecta();
        jButtonEditar.setEnabled(true);
        jButtonDeletar.setEnabled(true);
    }//GEN-LAST:event_jTableTabelaFilmeMouseClicked
    
    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"ID", "Título", "Entrada", "Gênero"};
        conex.conexao();
        conex.executaSql(Sql);
        
        try{
            conex.rs.first();
            do{
                dados.add(new Object[]{conex.rs.getInt("id_filme"), conex.rs.getString("titulo"), conex.rs.getDouble("valor_entrada"), conex.rs.getString("genero")});
            }while(conex.rs.next());
        }catch(SQLException ex){
            System.out.println("Erro ao Preencher ArrayList!"+ ex.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Nenhum Filme Corresponde à Pesquisa!");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        
        jTableTabelaFilme.setModel(modelo);
        jTableTabelaFilme.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTableTabelaFilme.getColumnModel().getColumn(0).setResizable(false);
        jTableTabelaFilme.getColumnModel().getColumn(1).setPreferredWidth(205);
        jTableTabelaFilme.getColumnModel().getColumn(1).setResizable(false);
        jTableTabelaFilme.getColumnModel().getColumn(2).setPreferredWidth(55);
        jTableTabelaFilme.getColumnModel().getColumn(2).setResizable(false);
        jTableTabelaFilme.getColumnModel().getColumn(3).setPreferredWidth(165);
        jTableTabelaFilme.getColumnModel().getColumn(3).setResizable(false);
        jTableTabelaFilme.getTableHeader().setReorderingAllowed(false);
        jTableTabelaFilme.setAutoResizeMode(jTableTabelaFilme.AUTO_RESIZE_OFF);
        jTableTabelaFilme.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        conex.desconecta();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTabelaFilme;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldPrecoFilme;
    private javax.swing.JTextField jTextFieldSinopse;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
