/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansLanche;
import modeloBeans.ModeloTabela;
import modeloConection.ConexaoBD;
import modeloDao.DaoLanche;

/**
 *
 * @author vinic
 */
public class FormLanche extends javax.swing.JFrame {
    
    BeansLanche mod = new BeansLanche();
    DaoLanche dao = new DaoLanche();
    ConexaoBD conex = new ConexaoBD();
    
    int flag = 0;
    
    public FormLanche() {
        initComponents();
        preencherTabela("select * from lanches order by nome_lanche");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPrecoLanche = new javax.swing.JTextField();
        jTextFieldIDLanche = new javax.swing.JTextField();
        jTextFieldNomeLanche = new javax.swing.JTextField();
        jTextFieldIngredientesLanche = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCadLanches = new javax.swing.JTable();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Preço:");

        jLabel1.setText("Nome:");

        jLabel3.setText("ID:");

        jLabel4.setText("Ingredientes");

        jTextFieldPrecoLanche.setEnabled(false);
        jTextFieldPrecoLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecoLancheActionPerformed(evt);
            }
        });

        jTextFieldIDLanche.setEnabled(false);

        jTextFieldNomeLanche.setEnabled(false);

        jTextFieldIngredientesLanche.setEnabled(false);

        jTableCadLanches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCadLanches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCadLanchesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCadLanches);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonDeletar.setText("Deletar");
        jButtonDeletar.setEnabled(false);
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jLabel6.setText("Buscar:");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNomeLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(170, 170, 170))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldIDLanche))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldPrecoLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldIngredientesLanche))))
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeletar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldPrecoLanche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIDLanche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNomeLanche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldIngredientesLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscar))
                        .addGap(16, 16, 16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Cadastro de Lanches");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(590, 417));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPrecoLancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecoLancheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecoLancheActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldNomeLanche.setEnabled(!true);
        jTextFieldIngredientesLanche.setEnabled(!true);
        jTextFieldPrecoLanche.setEnabled(!true);
        jTextFieldPesquisar.setEnabled(true);
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonDeletar.setEnabled(false);
        jTextFieldPesquisar.setEditable(true);
        jButtonBuscar.setEnabled(true);
        jTextFieldNomeLanche.setText("");
        jTextFieldIngredientesLanche.setText("");
        jTextFieldIDLanche.setText("");
        jTextFieldPrecoLanche.setText("");
        jTextFieldPesquisar.setText("");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jTextFieldNomeLanche.setEnabled(true);
        jTextFieldPrecoLanche.setEnabled(true);
        jTextFieldIngredientesLanche.setEnabled(true);
        jTextFieldPesquisar.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jTextFieldNomeLanche.setText("");
        jTextFieldIDLanche.setText("");
        jTextFieldPrecoLanche.setText("");
        jTextFieldIngredientesLanche.setText("");
        jTextFieldPesquisar.setText("");
        jButtonEditar.setEnabled(false);
        jButtonDeletar.setEnabled(false);
        jButtonBuscar.setEnabled(false);
        jButtonNovo.setEnabled(false);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if(jTextFieldNomeLanche.getText().isEmpty() || jTextFieldIngredientesLanche.getText().isEmpty() || jTextFieldPrecoLanche.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para continuar");
            //jTextFieldNome.requestFocus();
        }else{
            if(flag == 1){
                mod.setNomeLanche(jTextFieldNomeLanche.getText());
                mod.setIngredientesLanche(jTextFieldIngredientesLanche.getText());
                mod.setPrecoLanche(Double.parseDouble(jTextFieldPrecoLanche.getText()));
                dao.Salvar(mod);
                jTextFieldNomeLanche.setText("");
                jTextFieldIngredientesLanche.setText("");
                jTextFieldPrecoLanche.setText("");
                jTextFieldNomeLanche.setEnabled(true);
                jTextFieldPrecoLanche.setEnabled(true);
                jTextFieldIngredientesLanche.setEnabled(true);
                jTextFieldPesquisar.setEnabled(true);
                jButtonSalvar.setEnabled(false);
                jButtonCancelar.setEnabled(false);
                jButtonNovo.setEnabled(true);
                jButtonBuscar.setEnabled(true);
                jTextFieldNomeLanche.setText("");
                jTextFieldIDLanche.setText("");
                jTextFieldPrecoLanche.setText("");
                jTextFieldIngredientesLanche.setText("");
                preencherTabela("select * from lanches order by nome_lanche");
            }else{
                mod.setCodLanche(Integer.parseInt(jTextFieldIDLanche.getText()));
                mod.setNomeLanche(jTextFieldNomeLanche.getText());
                mod.setPrecoLanche(Double.parseDouble(jTextFieldPrecoLanche.getText()));
                mod.setIngredientesLanche(jTextFieldIngredientesLanche.getText());
                dao.Editar(mod);
                jTextFieldIDLanche.setText("");
                jTextFieldNomeLanche.setText("");
                jTextFieldPrecoLanche.setText("");
                jTextFieldIngredientesLanche.setText("");
                jTextFieldNomeLanche.setEnabled(false);
                jTextFieldPrecoLanche.setEnabled(false);
                jTextFieldIngredientesLanche.setEnabled(false);
                jTextFieldPesquisar.setEnabled(true);
                jButtonBuscar.setEnabled(true);
                jButtonSalvar.setEnabled(false);
                jButtonNovo.setEnabled(true);
                jButtonCancelar.setEnabled(false);
                preencherTabela("select * from lanches order by nome_lanche");
            }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;
        jTextFieldNomeLanche.setEnabled(true);
        jTextFieldIngredientesLanche.setEnabled(true);
        jTextFieldPrecoLanche.setEnabled(true);
        jTextFieldPesquisar.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonDeletar.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        mod.setPesquisa(jTextFieldPesquisar.getText());
        BeansLanche model = dao.buscaLanche(mod);
        jTextFieldNomeLanche.setText(model.getNomeLanche());
        jTextFieldIDLanche.setText(String.valueOf(model.getCodLanche()));
        jTextFieldPrecoLanche.setText(String.valueOf(model.getPrecoLanche()));
        jTextFieldIngredientesLanche.setText(model.getIngredientesLanche());
        jTextFieldNomeLanche.setEnabled(false);
        jTextFieldIngredientesLanche.setEnabled(false);
        jTextFieldPrecoLanche.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonDeletar.setEnabled(true);
        
        preencherTabela("select * from lanches where nome_lanche like'%" +mod.getPesquisa() +"%'");
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTableCadLanchesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCadLanchesMouseClicked
        String nome = ""+jTableCadLanches.getValueAt(jTableCadLanches.getSelectedRow(), 1);
        conex.conexao();
        conex.executaSql("select * from lanches where nome_lanche='"+ nome +"'");
        try{
            conex.rs.first();
            jTextFieldIDLanche.setText(String.valueOf(conex.rs.getInt("id_lanche")));
            jTextFieldNomeLanche.setText(String.valueOf(conex.rs.getString("nome_lanche")));
            jTextFieldPrecoLanche.setText(String.valueOf(conex.rs.getString("preco_lanche")));
            jTextFieldIngredientesLanche.setText(String.valueOf(conex.rs.getString("ingredientes_lanche")));
        }catch(SQLException ex){
            System.out.println("Erro ao Selecionar Dados: " +ex.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao Selecionar Dados!");
        }
        conex.desconecta();
        jButtonEditar.setEnabled(true);
        jButtonDeletar.setEnabled(true);
    }//GEN-LAST:event_jTableCadLanchesMouseClicked

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Excluir o Lanche Selecionado?");
        if(resposta == JOptionPane.YES_OPTION){
            mod.setCodLanche(Integer.parseInt(jTextFieldIDLanche.getText()));
            dao.ExcluirLanche(mod);
            jTextFieldIDLanche.setText("");
            jTextFieldNomeLanche.setText("");
            jTextFieldPrecoLanche.setText("");
            jTextFieldIngredientesLanche.setText("");
            jTextFieldPesquisar.setText("");
            jTextFieldNomeLanche.setEnabled(false);
            jTextFieldPrecoLanche.setEnabled(false);
            jTextFieldIngredientesLanche.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonDeletar.setEnabled(false);
            preencherTabela("select * from lanches order by nome_lanche");
        }
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"ID", "Nome", "Preço", "Ingredientes"};
        conex.conexao();
        conex.executaSql(Sql);
        
        try{
            conex.rs.first();
            do{
                dados.add(new Object[]{conex.rs.getInt("id_lanche"), conex.rs.getString("nome_lanche"), conex.rs.getDouble("preco_lanche"), conex.rs.getString("ingredientes_lanche")});
            }while(conex.rs.next());
        }catch(SQLException ex){
            System.out.println("Erro ao Preencher ArrayList!"+ ex.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Nenhum Lanche Corresponde à Pesquisa!");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        
        jTableCadLanches.setModel(modelo);
        jTableCadLanches.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTableCadLanches.getColumnModel().getColumn(0).setResizable(false);
        jTableCadLanches.getColumnModel().getColumn(1).setPreferredWidth(165);
        jTableCadLanches.getColumnModel().getColumn(1).setResizable(false);
        jTableCadLanches.getColumnModel().getColumn(2).setPreferredWidth(55);
        jTableCadLanches.getColumnModel().getColumn(2).setResizable(false);
        jTableCadLanches.getColumnModel().getColumn(3).setPreferredWidth(250);
        jTableCadLanches.getColumnModel().getColumn(3).setResizable(false);
        jTableCadLanches.getTableHeader().setReorderingAllowed(false);
        jTableCadLanches.setAutoResizeMode(jTableCadLanches.AUTO_RESIZE_OFF);
        jTableCadLanches.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        conex.desconecta();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLanche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCadLanches;
    private javax.swing.JTextField jTextFieldIDLanche;
    private javax.swing.JTextField jTextFieldIngredientesLanche;
    private javax.swing.JTextField jTextFieldNomeLanche;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldPrecoLanche;
    // End of variables declaration//GEN-END:variables
}
