package visao;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modeloConection.ConexaoBD;

/**
 *
 * @author vinic
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ConexaoBD conecta = new ConexaoBD();
    FormFuncionario CadFuncionario = new FormFuncionario();
    FormLanche CadLanche = new FormLanche();
    FormFilme CadFilme = new FormFilme();
    CartazFilmes cartaz = new CartazFilmes();
    
    public TelaPrincipal(String usuario) {
        initComponents();
        jLabelUsuario.setText(usuario);
        conecta.conexao();
    }

    private TelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInternal = new javax.swing.JPanel();
        jButtonCadLanches = new javax.swing.JButton();
        jButtonCadUsuario = new javax.swing.JButton();
        jButtonCadSessao = new javax.swing.JButton();
        jButtonVerCatalogo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelPainelFundo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonFecharBemVindo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelFundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuComprarIngresso = new javax.swing.JMenu();
        jMenuItemComprarIngresso = new javax.swing.JMenuItem();
        jMenuItemVerFilmes = new javax.swing.JMenuItem();
        jMenuLanches = new javax.swing.JMenu();
        jMenuTelaBemVindo = new javax.swing.JMenu();
        jMenuItemTelaBemVindo = new javax.swing.JMenuItem();
        jMenuGerenciamento = new javax.swing.JMenu();
        jMenuItemCadFuncionario = new javax.swing.JMenuItem();
        jMenuItemCadFilme = new javax.swing.JMenuItem();
        jMenuItemCadLanche = new javax.swing.JMenuItem();
        jMenuItemCadTodos = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setTitle("Bem-Vindo");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInternal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInternal.setLayout(null);

        jButtonCadLanches.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconeCadLanche.png"))); // NOI18N
        jButtonCadLanches.setToolTipText("Comprar Lanche");
        jButtonCadLanches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadLanchesActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadLanches);
        jButtonCadLanches.setBounds(230, 40, 80, 110);

        jButtonCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconeCadastraCliente.png"))); // NOI18N
        jButtonCadUsuario.setToolTipText("Cadastro");
        jButtonCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadUsuarioActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadUsuario);
        jButtonCadUsuario.setBounds(20, 40, 80, 110);

        jButtonCadSessao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconeBotaoIngresso.png"))); // NOI18N
        jButtonCadSessao.setToolTipText("Comprar Ingresso");
        jButtonCadSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadSessaoActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadSessao);
        jButtonCadSessao.setBounds(110, 40, 110, 110);

        jButtonVerCatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CatalogoDeFilmes.png"))); // NOI18N
        jButtonVerCatalogo.setToolTipText("Filmes em Cartaz");
        jButtonVerCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerCatalogoActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonVerCatalogo);
        jButtonVerCatalogo.setBounds(20, 160, 130, 120);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Opções:");
        jPanelInternal.add(jLabel2);
        jLabel2.setBounds(10, 10, 70, 19);

        jLabelPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ImternalFrame.jpg"))); // NOI18N
        jPanelInternal.add(jLabelPainelFundo);
        jLabelPainelFundo.setBounds(0, 0, 630, 300);

        jInternalFrameBemVindo.getContentPane().add(jPanelInternal);
        jPanelInternal.setBounds(0, 40, 630, 290);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Bem-Vindo ao JavaCine");
        jInternalFrameBemVindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 260, 24);

        jButtonFecharBemVindo.setBackground(new java.awt.Color(255, 102, 102));
        jButtonFecharBemVindo.setForeground(new java.awt.Color(255, 153, 153));
        jButtonFecharBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconeFechar.png"))); // NOI18N
        jButtonFecharBemVindo.setToolTipText("Fechar Tela Bem-Vindo");
        jButtonFecharBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharBemVindoActionPerformed(evt);
            }
        });
        jInternalFrameBemVindo.getContentPane().add(jButtonFecharBemVindo);
        jButtonFecharBemVindo.setBounds(570, 0, 50, 40);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(0, 70, 630, 350);

        jLabel3.setText("Usuário:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 420, 60, 16);

        jLabelUsuario.setText("jLabel4");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(70, 420, 190, 16);

        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PlanodeFundo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoPrincipal);
        jLabelFundoPrincipal.setBounds(0, 0, 630, 440);

        jMenuComprarIngresso.setText("Ingressos");

        jMenuItemComprarIngresso.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItemComprarIngresso.setText("Comprar Ingresso");
        jMenuItemComprarIngresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemComprarIngressoActionPerformed(evt);
            }
        });
        jMenuComprarIngresso.add(jMenuItemComprarIngresso);

        jMenuItemVerFilmes.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItemVerFilmes.setText("Filmes em Cartaz");
        jMenuItemVerFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerFilmesActionPerformed(evt);
            }
        });
        jMenuComprarIngresso.add(jMenuItemVerFilmes);

        jMenuBar1.add(jMenuComprarIngresso);

        jMenuLanches.setText("Lanches");
        jMenuLanches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLanchesMouseClicked(evt);
            }
        });
        jMenuLanches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLanchesActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuLanches);

        jMenuTelaBemVindo.setText("Tela");

        jMenuItemTelaBemVindo.setText("Tela Bem-Vindo");
        jMenuItemTelaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBemVindoActionPerformed(evt);
            }
        });
        jMenuTelaBemVindo.add(jMenuItemTelaBemVindo);

        jMenuBar1.add(jMenuTelaBemVindo);

        jMenuGerenciamento.setText("Gerenciamento");
        jMenuGerenciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGerenciamentoActionPerformed(evt);
            }
        });

        jMenuItemCadFuncionario.setText("Funcionários");
        jMenuItemCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadFuncionarioActionPerformed(evt);
            }
        });
        jMenuGerenciamento.add(jMenuItemCadFuncionario);

        jMenuItemCadFilme.setText("Filmes");
        jMenuItemCadFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadFilmeActionPerformed(evt);
            }
        });
        jMenuGerenciamento.add(jMenuItemCadFilme);

        jMenuItemCadLanche.setText("Lanches");
        jMenuItemCadLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadLancheActionPerformed(evt);
            }
        });
        jMenuGerenciamento.add(jMenuItemCadLanche);

        jMenuItemCadTodos.setText("Geral");
        jMenuItemCadTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadTodosActionPerformed(evt);
            }
        });
        jMenuGerenciamento.add(jMenuItemCadTodos);

        jMenuBar1.add(jMenuGerenciamento);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(642, 503));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemComprarIngressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemComprarIngressoActionPerformed
        TelaEscolhaFilme telaFilme = new TelaEscolhaFilme(jLabelUsuario.getText());
        telaFilme.setVisible(true);
        telaFilme.setResizable(false);
    }//GEN-LAST:event_jMenuItemComprarIngressoActionPerformed

    private void jMenuItemVerFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerFilmesActionPerformed
        if(cartaz == null){
            cartaz = new CartazFilmes();
            cartaz.setVisible(true);
            cartaz.setResizable(false);
        }else{
            cartaz.setVisible(true);
            cartaz.setResizable(false);
        }
    }//GEN-LAST:event_jMenuItemVerFilmesActionPerformed

    private void jMenuItemCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadFuncionarioActionPerformed
        try {
            conecta.executaSql("select * from usuarios where nome_usuario='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            System.out.println(conecta.rs.getString("usu_tipo"));
            if(conecta.rs.getString("usu_tipo").trim().equals("Administrador")){
                if(CadFuncionario == null){
                    CadFuncionario = new FormFuncionario();
                    CadFuncionario.setVisible(true);
                    CadFuncionario.setResizable(false);
                }else{
                    CadFuncionario.setVisible(true);
                    CadFuncionario.setResizable(false);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você nâo tem permissão para essa funcionalidade!\n Contate o admistrador do sistema");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Você nâo tem permissão para essa funcionalidade!\n Contate o admistrador do sistema");
        }
    }//GEN-LAST:event_jMenuItemCadFuncionarioActionPerformed

    private void jMenuItemCadFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadFilmeActionPerformed
        try {
            conecta.executaSql("select * from usuarios where nome_usuario='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            System.out.println(conecta.rs.getString("usu_tipo"));
            if(conecta.rs.getString("usu_tipo").trim().equals("Administrador")){
                if(CadFilme == null){
                    CadFilme = new FormFilme();
                    CadFilme.setVisible(true);
                    CadFilme.setResizable(false);
                }else{
                    CadFilme.setVisible(true);
                    CadFilme.setResizable(false);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você nâo tem permissão para essa funcionalidade!\n Contate o admistrador do sistema");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Você nâo tem permissão para essa funcionalidade!\n Contate o admistrador do sistema");
        }
    }//GEN-LAST:event_jMenuItemCadFilmeActionPerformed

    private void jMenuGerenciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGerenciamentoActionPerformed
        
    }//GEN-LAST:event_jMenuGerenciamentoActionPerformed

    private void jMenuItemCadTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadTodosActionPerformed
        try {
            conecta.executaSql("select * from usuarios where nome_usuario='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            System.out.println(conecta.rs.getString("usu_tipo"));
            if(conecta.rs.getString("usu_tipo").trim().equals("Administrador")){
                TelaCadastros telaCad = new TelaCadastros(jLabelUsuario.getText());
                telaCad.setVisible(true);
                telaCad.setResizable(false);
                dispose();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você nâo tem permissão para essa funcionalidade!\n Contate o admistrador do sistema");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Você nâo tem permissão para essa funcionalidade!\n Contate o admistrador do sistema");
        }




        //TelaCadastros telaCad = new TelaCadastros();
        //telaCad.setVisible(true);
        //dispose();
    }//GEN-LAST:event_jMenuItemCadTodosActionPerformed

    private void jButtonFecharBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharBemVindoActionPerformed
        jInternalFrameBemVindo.dispose();
    }//GEN-LAST:event_jButtonFecharBemVindoActionPerformed

    private void jMenuItemTelaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBemVindoActionPerformed
         //TelaPrincipal telaPrin = new TelaPrincipal();
         jInternalFrameBemVindo.setVisible(true);
    }//GEN-LAST:event_jMenuItemTelaBemVindoActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jButtonCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadUsuarioActionPerformed
        FormUsuario tela = new FormUsuario(jLabelUsuario.getText());
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadUsuarioActionPerformed

    private void jMenuItemCadLancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadLancheActionPerformed
        try {
            conecta.executaSql("select * from usuarios where nome_usuario='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            System.out.println(conecta.rs.getString("usu_tipo"));
            if(conecta.rs.getString("usu_tipo").trim().equals("Administrador")){
                if(CadLanche == null){
                    CadLanche = new FormLanche();
                    CadLanche.setVisible(true);
                    CadLanche.setResizable(false);
                }else{
                    CadLanche.setVisible(true);
                    CadLanche.setResizable(false);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você nâo tem permissão para essa funcionalidade!\n Contate o admistrador do sistema");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Você nâo tem permissão para essa funcionalidade!\n Contate o admistrador do sistema");
        }
    }//GEN-LAST:event_jMenuItemCadLancheActionPerformed

    private void jButtonVerCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerCatalogoActionPerformed
        if(cartaz == null){
            cartaz = new CartazFilmes();
            cartaz.setVisible(true);
            cartaz.setResizable(false);
        }else{
            cartaz.setVisible(true);
            cartaz.setResizable(false);
        }
    }//GEN-LAST:event_jButtonVerCatalogoActionPerformed

    private void jButtonCadLanchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadLanchesActionPerformed
       TelaEscolhaLanche telaLanche = new TelaEscolhaLanche(jLabelUsuario.getText());
       telaLanche.setVisible(true);
       telaLanche.setResizable(false);        
    }//GEN-LAST:event_jButtonCadLanchesActionPerformed

    private void jButtonCadSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadSessaoActionPerformed
        TelaEscolhaFilme telaFilme = new TelaEscolhaFilme(jLabelUsuario.getText());
        telaFilme.setVisible(true);
        telaFilme.setResizable(false);
    }//GEN-LAST:event_jButtonCadSessaoActionPerformed

    private void jMenuLanchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLanchesActionPerformed
        TelaEscolhaLanche telaLanche = new TelaEscolhaLanche(jLabelUsuario.getText());
        telaLanche.setVisible(true);
        telaLanche.setResizable(false);
    }//GEN-LAST:event_jMenuLanchesActionPerformed

    private void jMenuLanchesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLanchesMouseClicked
        TelaEscolhaLanche telaLanche = new TelaEscolhaLanche(jLabelUsuario.getText());
        telaLanche.setVisible(true);
        telaLanche.setResizable(false);
    }//GEN-LAST:event_jMenuLanchesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadLanches;
    private javax.swing.JButton jButtonCadSessao;
    private javax.swing.JButton jButtonCadUsuario;
    private javax.swing.JButton jButtonFecharBemVindo;
    private javax.swing.JButton jButtonVerCatalogo;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFundoPrincipal;
    private javax.swing.JLabel jLabelPainelFundo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuComprarIngresso;
    private javax.swing.JMenu jMenuGerenciamento;
    private javax.swing.JMenuItem jMenuItemCadFilme;
    private javax.swing.JMenuItem jMenuItemCadFuncionario;
    private javax.swing.JMenuItem jMenuItemCadLanche;
    private javax.swing.JMenuItem jMenuItemCadTodos;
    private javax.swing.JMenuItem jMenuItemComprarIngresso;
    private javax.swing.JMenuItem jMenuItemTelaBemVindo;
    private javax.swing.JMenuItem jMenuItemVerFilmes;
    private javax.swing.JMenu jMenuLanches;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuTelaBemVindo;
    private javax.swing.JPanel jPanelInternal;
    // End of variables declaration//GEN-END:variables
}
