package visao;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import modeloConection.ConexaoBD;

/**
 *
 * @author vinic
 */
public class TelaCadastros extends javax.swing.JFrame {
    
    ConexaoBD  conecta = new ConexaoBD();
    FormFuncionario CadFuncionario = new FormFuncionario();
    FormLanche CadLanche = new FormLanche();
    FormFilme CadFilme = new FormFilme();
    CartazFilmes cartaz = new CartazFilmes();
    
    public TelaCadastros(String usuario) {
        initComponents();
        jLabelUsuarioCad.setText(usuario);
    }

    private TelaCadastros() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameGerenciamento = new javax.swing.JInternalFrame();
        jPanelInternal = new javax.swing.JPanel();
        jButtonCadUsuario = new javax.swing.JButton();
        jButtonCadLanches = new javax.swing.JButton();
        jButtonCadFuncionario = new javax.swing.JButton();
        jButtonCadSessao = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelPainelFundo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonFecharTelaGerenciamento = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelUsuarioCad = new javax.swing.JLabel();
        jLabelFundoGerenciamento = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuComprarIngresso = new javax.swing.JMenu();
        jMenuItemComprarIngresso = new javax.swing.JMenuItem();
        jMenuItemVerFilmes = new javax.swing.JMenuItem();
        jMenuLanches = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemTelaGerenciamento = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuGerenciamento = new javax.swing.JMenu();
        jMenuItemCadFuncionario = new javax.swing.JMenuItem();
        jMenuItemCadFilmes = new javax.swing.JMenuItem();
        jMenuItemCadLanche = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameGerenciamento.setTitle("Bem-Vindo");
        jInternalFrameGerenciamento.setVisible(true);
        jInternalFrameGerenciamento.getContentPane().setLayout(null);

        jPanelInternal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInternal.setLayout(null);

        jButtonCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconeCadastraCliente.png"))); // NOI18N
        jButtonCadUsuario.setToolTipText("Usuários");
        jButtonCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadUsuarioActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadUsuario);
        jButtonCadUsuario.setBounds(510, 40, 80, 110);

        jButtonCadLanches.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconeCadLanche.png"))); // NOI18N
        jButtonCadLanches.setToolTipText("Lanche");
        jButtonCadLanches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadLanchesActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadLanches);
        jButtonCadLanches.setBounds(420, 40, 80, 110);

        jButtonCadFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconeFuncionario1.png"))); // NOI18N
        jButtonCadFuncionario.setToolTipText("Funcionário");
        jButtonCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadFuncionarioActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadFuncionario);
        jButtonCadFuncionario.setBounds(210, 40, 80, 110);

        jButtonCadSessao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconeAlocarSessao.png"))); // NOI18N
        jButtonCadSessao.setToolTipText("Filme");
        jButtonCadSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadSessaoActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadSessao);
        jButtonCadSessao.setBounds(300, 40, 110, 110);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cadastros:");
        jPanelInternal.add(jLabel2);
        jLabel2.setBounds(200, 0, 90, 19);

        jLabelPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ImternalFrame.jpg"))); // NOI18N
        jPanelInternal.add(jLabelPainelFundo);
        jLabelPainelFundo.setBounds(0, 0, 630, 300);

        jInternalFrameGerenciamento.getContentPane().add(jPanelInternal);
        jPanelInternal.setBounds(0, 40, 630, 290);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Gerenciamento do JavaCine");
        jInternalFrameGerenciamento.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 260, 24);

        jButtonFecharTelaGerenciamento.setBackground(new java.awt.Color(255, 51, 51));
        jButtonFecharTelaGerenciamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconeFechar.png"))); // NOI18N
        jButtonFecharTelaGerenciamento.setToolTipText("Fechar Tela Gerenciamento");
        jButtonFecharTelaGerenciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharTelaGerenciamentoActionPerformed(evt);
            }
        });
        jInternalFrameGerenciamento.getContentPane().add(jButtonFecharTelaGerenciamento);
        jButtonFecharTelaGerenciamento.setBounds(570, 0, 50, 40);

        getContentPane().add(jInternalFrameGerenciamento);
        jInternalFrameGerenciamento.setBounds(0, 40, 630, 350);

        jLabel3.setText("Usuário: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 390, 60, 20);

        jLabelUsuarioCad.setText("jLabel4");
        getContentPane().add(jLabelUsuarioCad);
        jLabelUsuarioCad.setBounds(70, 390, 160, 16);

        jLabelFundoGerenciamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FundoTelaGerenciamento.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoGerenciamento);
        jLabelFundoGerenciamento.setBounds(0, 0, 630, 460);

        jMenuComprarIngresso.setText("Ingressos");

        jMenuItemComprarIngresso.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItemComprarIngresso.setText("Comprar Ingresso");
        jMenuItemComprarIngresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemComprarIngressoActionPerformed(evt);
            }
        });
        jMenuComprarIngresso.add(jMenuItemComprarIngresso);

        jMenuItemVerFilmes.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItemVerFilmes.setText("Filmes em Cartaz");
        jMenuItemVerFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerFilmesActionPerformed(evt);
            }
        });
        jMenuComprarIngresso.add(jMenuItemVerFilmes);

        jMenuBar1.add(jMenuComprarIngresso);

        jMenuLanches.setText("Lanches");
        jMenuLanches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLanchesMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuLanches);

        jMenu1.setText("Tela");

        jMenuItemTelaGerenciamento.setText("Tela Gerenciamento");
        jMenuItemTelaGerenciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaGerenciamentoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTelaGerenciamento);

        jMenuItem1.setText("Tela Principal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenuGerenciamento.setText("Gerenciamento");

        jMenuItemCadFuncionario.setText("Funcionários");
        jMenuItemCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadFuncionarioActionPerformed(evt);
            }
        });
        jMenuGerenciamento.add(jMenuItemCadFuncionario);

        jMenuItemCadFilmes.setText("Filmes");
        jMenuItemCadFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadFilmesActionPerformed(evt);
            }
        });
        jMenuGerenciamento.add(jMenuItemCadFilmes);

        jMenuItemCadLanche.setText("Lanches");
        jMenuItemCadLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadLancheActionPerformed(evt);
            }
        });
        jMenuGerenciamento.add(jMenuItemCadLanche);

        jMenuBar1.add(jMenuGerenciamento);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(647, 475));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemComprarIngressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemComprarIngressoActionPerformed
        TelaEscolhaFilme telaFilme = new TelaEscolhaFilme(jLabelUsuarioCad.getText());
        telaFilme.setVisible(true);
        telaFilme.setResizable(false);
    }//GEN-LAST:event_jMenuItemComprarIngressoActionPerformed

    private void jMenuItemVerFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerFilmesActionPerformed
        if(cartaz == null){
            cartaz = new CartazFilmes();
            cartaz.setVisible(true);
            cartaz.setResizable(false);
        }else{
            cartaz.setVisible(true);
            cartaz.setResizable(false);
        }
    }//GEN-LAST:event_jMenuItemVerFilmesActionPerformed

    private void jMenuItemCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadFuncionarioActionPerformed
        if(CadFuncionario == null){
            CadFuncionario = new FormFuncionario();
            CadFuncionario.setVisible(true);
            CadFuncionario.setResizable(false);
        }else{
            CadFuncionario.setVisible(true);
            CadFuncionario.setResizable(false);
        }
    }//GEN-LAST:event_jMenuItemCadFuncionarioActionPerformed

    private void jMenuItemCadFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadFilmesActionPerformed
        if(CadFilme == null){
            CadFilme = new FormFilme();
            CadFilme.setVisible(true);
            CadFilme.setResizable(false);
        }else{
            CadFilme.setVisible(true);
            CadFilme.setResizable(false);
        }
    }//GEN-LAST:event_jMenuItemCadFilmesActionPerformed

    private void jButtonFecharTelaGerenciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharTelaGerenciamentoActionPerformed
        jInternalFrameGerenciamento.dispose();
    }//GEN-LAST:event_jButtonFecharTelaGerenciamentoActionPerformed

    private void jMenuItemTelaGerenciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaGerenciamentoActionPerformed
        jInternalFrameGerenciamento.setVisible(true);
    }//GEN-LAST:event_jMenuItemTelaGerenciamentoActionPerformed

    private void jButtonCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadFuncionarioActionPerformed
        if(CadFuncionario == null){
            CadFuncionario = new FormFuncionario();
            CadFuncionario.setVisible(true);
            CadFuncionario.setResizable(false);
        }else{
            CadFuncionario.setVisible(true);
            CadFuncionario.setResizable(false);
        }
    }//GEN-LAST:event_jButtonCadFuncionarioActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jMenuItemCadLancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadLancheActionPerformed
        if(CadLanche == null){
            CadLanche = new FormLanche();
            CadLanche.setVisible(true);
            CadLanche.setResizable(false);
        }else{
            CadLanche.setVisible(true);
            CadLanche.setResizable(false);
        }
    }//GEN-LAST:event_jMenuItemCadLancheActionPerformed

    private void jButtonCadLanchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadLanchesActionPerformed
        if(CadLanche == null){
            CadLanche = new FormLanche();
            CadLanche.setVisible(true);
            CadLanche.setResizable(false);
        }else{
            CadLanche.setVisible(true);
            CadLanche.setResizable(false);
        }
    }//GEN-LAST:event_jButtonCadLanchesActionPerformed

    private void jButtonCadSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadSessaoActionPerformed
        if(CadFilme == null){
            CadFilme = new FormFilme();
            CadFilme.setVisible(true);
            CadFilme.setResizable(false);
        }else{
            CadFilme.setVisible(true);
            CadFilme.setResizable(false);
        }
    }//GEN-LAST:event_jButtonCadSessaoActionPerformed

    private void jMenuLanchesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLanchesMouseClicked
        TelaEscolhaLanche telaLanche = new TelaEscolhaLanche(jLabelUsuarioCad.getText());
        telaLanche.setVisible(true);
        telaLanche.setResizable(false);
    }//GEN-LAST:event_jMenuLanchesMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaPrincipal tela = new TelaPrincipal(jLabelUsuarioCad.getText());
        tela.setVisible(true);
        tela.setResizable(false);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButtonCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadUsuarioActionPerformed
        FormUsuario tela = new FormUsuario(jLabelUsuarioCad.getText());
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadFuncionario;
    private javax.swing.JButton jButtonCadLanches;
    private javax.swing.JButton jButtonCadSessao;
    private javax.swing.JButton jButtonCadUsuario;
    private javax.swing.JButton jButtonFecharTelaGerenciamento;
    private javax.swing.JInternalFrame jInternalFrameGerenciamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFundoGerenciamento;
    private javax.swing.JLabel jLabelPainelFundo;
    private javax.swing.JLabel jLabelUsuarioCad;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuComprarIngresso;
    private javax.swing.JMenu jMenuGerenciamento;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemCadFilmes;
    private javax.swing.JMenuItem jMenuItemCadFuncionario;
    private javax.swing.JMenuItem jMenuItemCadLanche;
    private javax.swing.JMenuItem jMenuItemComprarIngresso;
    private javax.swing.JMenuItem jMenuItemTelaGerenciamento;
    private javax.swing.JMenuItem jMenuItemVerFilmes;
    private javax.swing.JMenu jMenuLanches;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInternal;
    // End of variables declaration//GEN-END:variables
}
